
object Versions {
    const val kotlin = "1.6.21"
    const val timber = "5.0.1"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.1"
    const val jUnit = "4.13.2"
    const val androidx = "1.6.0"
    const val lifecycleKtx = "2.3.1"
    const val navigationKtx = "2.3.5"
    const val junitExt = "1.1.2"
    const val espresso = "3.3.0"
    const val daggerVersion = "2.25.2"
    const val circleImageView = "3.1.0"
    const val coordinator = "1.1.0"
    const val gson = "2.8.9"
    const val okhttp = "4.9.0"
    const val retrofit = "2.9.0"
    const val eventBus = "3.2.0"
    const val security = "1.1.0-alpha01"
    const val rxKotlin = "3.0.1"
    const val calendarView = "1.0.4"
    const val desugar = "1.1.5"
    const val vk = "2.2.3"
    const val ok = "2.0.3"
    const val google = "20.1.0"
    const val spinner = "1.1.9"
    const val colorPicker = "0.2.2"
    const val paging3 = "3.1.1"
    const val recycler = "1.2.1"
    const val firebaseBom = "30.0.0"
    const val firebaseMessaging = "23.0.4"
}